booksite/booksite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'booksite.views.home', name='home'),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^admin/', include(admin.site.urls)),
]

booksite/catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /catalog/
    url(r'^$', views.index, name='index'),
    # ex: /catalog/add/publisher/
    url(r'^add/publisher/$', views.add_publisher, name='add_publisher'),
    # ex: /catalog/add/title/
    url(r'^add/title/$', views.add_title, name='add_title'),
    # ex: /catalog/get/titles/by/publisher/
    url(r'^get/titles/by/publisher/$', views.get_titles_by_publisher, name='get_titles_by_publisher'),
    # ex:/catalog/get/publisher/of/title/
    url(r'^get/publisher/of/title/$', views.get_publisher_of_title, name='get_publisher_of_title'),
]

booksite/catalog/models.py
from django.db import models

class Publisher(models.Model):
    pub_id=models.IntegerField(primary_key=True,unique=True)
    pub_name = models.CharField(max_length=50,unique=True)
    city = models.CharField(max_length=50)
    def __unicode__(self):
	return u'%s' %(self.pub_name)

class Title(models.Model):
    title_id=models.CharField(primary_key=True,max_length=20)
    title = models.CharField(max_length=100)
    category=models.CharField(max_length=20)
    price = models.FloatField(null=True, blank=True)
    pub_id=models.ForeignKey("Publisher")
    def __unicode__(self):
	return u'%s' %(self.title)
#from catalog.models import Publisher,Title

booksite/catalog/forms.py
# Forms used by the catalog "app" of the booksite project
from django import forms
from .models import Publisher, Title

class PublisherSearchForm(forms.Form):
    ''' Used to select a publisher -- user enters publisher's name
    '''
    publisher = forms.CharField(label='Get titles of: ', max_length=100)

class TitleSearchForm(forms.Form):
    ''' Used to select a title -- user enters the whole title
    '''
    title = forms.CharField(label='Title to find', max_length=100)

class PublisherForm(forms.ModelForm):
    ''' Form for adding a publisher
    '''
    class Meta:
        model = Publisher
        fields = ('pub_id', 'pub_name', 'city')

class TitleForm(forms.ModelForm):
    ''' Form for adding a title
    '''
    class Meta:
        model = Title
        fields = ('title_id', 'title', 'category', 'price', 'pub_id')

    # def clean_name(self):
        # custom validation -- in the Titles database,
        # could check the prefix of the title ID, which matches
        # the type field (here renamed category) unless that is "UNDECIDED"

booksite/catalog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

# view used by the catalog app
from .models import Publisher, Title
from .forms import PublisherForm, TitleForm, PublisherSearchForm, TitleSearchForm

def index(request):
    ''' Index page to provide links to the different options
    '''
    return render(request, 'index.html')

# Sloppy versions of the views -- a lot of duplicate code :(
def add_publisher(request):
    ''' View to add a publisher
    '''
    # edited from code on https://docs.djangoproject.com/en/1.8/topics/forms/
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PublisherForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/thanks/')
            form.save()
            return HttpResponseRedirect('/catalog/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PublisherForm()

    return render(request, 'add_publisher.html', {'form': form})

def add_title(request):
    ''' View to add a title -- needs publisher to have already been added
    '''
    # edited from code on https://docs.djangoproject.com/en/1.8/topics/forms/
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TitleForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/thanks/')
            form.save()
            return HttpResponseRedirect('/catalog/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = TitleForm()

    return render(request, 'add_title.html', {'form': form})

def get_titles_by_publisher(request):
    ''' View to find titles of a specific publisher
    '''
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PublisherSearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            target_publisher = form.cleaned_data['publisher']
            try:
                publisher = Publisher.objects.get(pub_name=target_publisher)
                title_list = Title.objects.filter(pub_id=publisher.pub_id)
            except Publisher.DoesNotExist:
                publisher = None
            return render(request, 'get_titles_by_publisher.html', {'result':True, 'publisher': publisher, 'title_list': title_list})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PublisherSearchForm()

    return render(request, 'get_titles_by_publisher.html', {'form': form})

def get_publisher_of_title(request):
    ''' View to find publisher of a specific title
    '''
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TitleSearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            target_title = form.cleaned_data['title']
            try:
                publisher = Title.objects.get(title=target_title)
            except Title.DoesNotExist:
                publisher = None
            return render(request, 'get_publisher_of_title.html', {'result':True, 'publisher': publisher})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = TitleSearchForm()

    return render(request, 'get_publisher_of_title.html', {'form': form})

booksite/catalog/templates/catalog/add_publisher.html
<h2>Add a New Publisher</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/catalog/add/publisher/" method="post">
    <!-- Next line provides standard Django mechanism for preventing cross-site request forgeries -->
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

<a href="/catalog/">Return to Index</a>

booksite/catalog/templates/catalog/add_title.html
<h2>Add a New Title</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/catalog/add/title/" method="post">
    <!-- Next line provides standard Django mechanism for preventing cross-site request forgeries -->
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

<a href="/catalog/">Return to Index</a>

booksite/catalog/templates/catalog/get_publisher_of_title.html
<h2>Find Publisher of Title</h2>

{% if result %}
    {% if publisher %}
        <p>The publisher is {{ publisher.pub_id.pub_name }}</p>
    {% else %}
	<p>The title was not found.</p>
    {% endif %}
{% endif %}

<form action="/catalog/get/publisher/of/title/" method="post">
    <!-- Next line provides standard Django mechanism for preventing cross-site request forgeries -->
    {% csrf_token %}
    <label for="id_title">Title:</label><input id="id_title" maxlength="100" name="title" type="text" />
    <input type="submit" value="Lookup" />
</form>
<a href="/catalog/">Return to Index</a>

booksite/catalog/templates/catalog/get_titles_by_publisher.html
<h2>Find Titles of a Publisher</h2>

{% if result %}
    {% if title_list %}
        <p>For {{ publisher.pub_name }}:</p>
        <ul>
        {% for book in title_list %}
            <li>{{ book.title }} {{ book.price }}</li>
        {% endfor %}
        </ul>
    {% else %}
	<p>No titles by the publisher are available.</p>
    {% endif %}
{% else %}
    <form action="/catalog/get/titles/by/publisher/" method="post">
        <!-- Next line provides standard Django mechanism for preventing cross-site request forgeries -->
        {% csrf_token %}
        <label for="id_publisher">Publisher:</label><input id="id_publisher" maxlength="100" name="publisher" type="text" />
        <input type="submit" value="Lookup" />
    </form>
{% endif %}
<a href="/catalog/">Return to Index</a>


booksite/catalog/templates/catalog/index.html
<!-- The index page template.

The { %, % }'s (the template processor ignores HTML, including
comments, so the spaces have been added to avoid getting processed)
mark the code the template processor will handle.

The code is able to access variables from the python view code,
but while keywords like "if" and "for" behave like their Python
counterparts, general Python syntax is not supported
-->
<h2>Django interface for an early version of the Microsoft "pubs" database</h2>

The functionality supported includes:
<ul>
<li>
<a href="add/publisher/">Add a publisher</a>
</li>
<li>
<a href="add/title/">Add a title</a> (publisher must have already been added)
</li>
<li>
<a href="get/titles/by/publisher/">Get all titles from a single publisher</a>
</li>
<li>
<a href="get/publisher/of/title/">Find the publisher of a title</a> (Must know full title)
</li>
</ul>